# This workflow will build a .NET project

name: .NET

on:
  push:
    paths:
      - "**.cs"
      - "**.csproj"
      - "**.sln"
      - "**.resx"
      - "**.vsixmanifest"
      - "**.ps1"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK 3.1.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
